config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  root to: 'articles#index'

  resources :articles

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  scope module: :apps do
    resources :favorites, only: [:index]
    resource :profile, only: [:show, :edit, :update]
    resource :timeline, only: [:show]
  end

  namespace :api, defaults: {format: :json} do
    scope "articles/:article_id" do
      resources :comments, only: [:index, :create]
      resource :like, only: [:show, :create, :destroy]
    end
  end


end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  has_one_attached :eyecatch
  has_rich_text :content

  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100}
  validates :title, format: { with: /\A(?!\@)/ }

  validates :content, presence: true
  # validates :content, length: { minimum: 10 }
  # validates :content, uniqueness: true

  # validate :validate_title_and_content_length

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user



  private
  # def validate_title_and_content_length
  #   char_count = self.title.length + self.content.length
  #   errors.add(:content, '100文字以上で！') unless char_count > 100
  # end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: '保存できたよ'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy!
    redirect_to root_path,notice: '削除に成功しました'
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :eyecatch)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :eyecatch, "アイキャッチ"
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, "タイトル"
    %div
      = f.text_field :title, class: "text"
    %div
      = f.label :content, "内容"
    %div
      = f.rich_text_area :content
    = f.submit "保存", class: "btn-primary"

app/views/articles/edit.html.haml
= render "form", article: @article

app/views/articles/index.html.haml
= render "commons/articles", articles: @articles

app/views/articles/new.html.haml
= render "form", article: @article

app/views/articles/show.html.haml
.article#article-show{data: {article_id: @article.id}}
  - if @article.eyecatch.attached?
    .article_image
      = image_tag @article.eyecatch
  %h1.article_title= @article.title
  .article_detail
    = link_to account_path(@article.user) do
      = image_tag @article.user.avatar_image
    %div
      %p= @article.author_name
      %p= @article.display_created_at
    - if user_signed_in? && current_user.has_written?(@article)
      .article_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to "編集する", edit_article_path(@article)
            = link_to "削除する", article_path(@article), data: {method: "delete", confirm: "本当に削除してもよろしいですか？"}
  .article_content
    = @article.content
  - if user_signed_in?
    .article_heart.hidden.active-heart
      = image_tag 'heart-active.svg'
    .article_heart.hidden.inactive-heart
      = image_tag 'heart.svg'

.article
  %h2= I18n.t("articles.comment_list")
  .comments-container

.container
  .btn-secondary.show-comment-form
    コメントを追加
  .comment-text-area.hidden
    = text_area_tag :comment_content, "", class: "sm"
    .btn-secondary.add-comment-button
      コメントを追加

= javascript_pack_tag "article"