config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  root to: 'articles#index'

  resources :articles

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  scope module: :apps do
    resources :favorites, only: [:index]
    resource :profile, only: [:show, :edit, :update]
    resource :timeline, only: [:show]
  end

  namespace :api, defaults: {format: :json} do
    scope "articles/:article_id" do
      resources :comments, only: [:index, :create]
      resource :like, only: [:show, :create, :destroy]
    end
  end


end

app/views/layouts/_footer.html.haml
%footer.footer-container
  - if I18n.locale == :en
    = link_to "日本語", url_for(locale: :ja)
  - else
    = link_to "English", url_for(locale: :en)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DailyTrial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag "back.svg", class: "header_back"
        %p.header_pageTitle
          = link_to 'BlogApp', root_path
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: "header_avatar dropbtn"
          .dropdown-content
            = link_to "プロフィール", profile_path
            = link_to "お気に入り", favorites_path
            = link_to "ログアウト", destroy_user_session_path, data: { method: "delete" }
      - else
        = link_to "ログイン", new_user_session_path, class: "header_loginBtn"
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield
    = render "layouts/footer"